name: code-refactor

on:
    push:
        branches:
            - master

jobs:
  code-refactor:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install
      run: npm install
      env:
        CI: true

    - name: Run prettier
      run: npx prettier --write 'src/**/*.{css,scss,jsx,js,vue}' --config .prettierrc

    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Refactor code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}